module.exports = {
  WHITESPACE: 'whitespace',
  NEWLINE: 'newline',
  OPERAND_SEPARATOR: 'operand_separator',
  LABEL: 'label',

  LD: 'ld',
  ADD: 'add',
  SUB: 'sub',
  SUBS: 'subs',
  CMP: 'cmp',
  NOP: 'nop',
  AND: 'and',
  OR: 'or',
  XOR: 'xor',
  NOT: 'not',
  LSF: 'lsf',
  RSF: 'rsf',
  JZ: 'jz',
  JNZ: 'jnz',
  JEQ: 'jeq',
  JNE: 'jne',
  JG: 'jg',
  JL: 'jl',
  PSH: 'psh',
  POP: 'pop',
  SWP: 'swp',

  HEX_VALUE: 'hex_value',
  DEC_VALUE: 'dec_value',

  REG_A: 'reg_a',
  REG_B: 'reg_b',
  REG_C: 'reg_c',
  REG_D: 'reg_d',

  PTR_A: 'ptr_a',
  PTR_B: 'ptr_b',
  PTR_C: 'ptr_c',
  PTR_D: 'ptr_d',

  ENTRY_POINT: 'entry_point',
  DATA_START: 'data_start',
  DATA_END: 'data_end',
  TEXT_SECTION: 'text_section'
};
